all:
  children:
    dns:
      hosts:
        shack-dns-p001:
          ansible_host: 10.0.0.6
          pihole_dhcp_enabled: true
          pihole_sync_source: true
          keepalived_state: "MASTER"
          keepalived_priority: 110
          keepalived_peer_ip: "10.0.0.7"

        shack-dns-p002:
          ansible_host: 10.0.0.7
          pihole_dhcp_enabled: false
          pihole_sync_source: false
          keepalived_state: "BACKUP"
          keepalived_priority: 100
          keepalived_peer_ip: "10.0.0.6"
