all:
  children:
    dns:
      hosts:
        shack-dns-p001:
          ansible_host: 10.0.0.6
          dns_keepalived_priority: 200
          pihole_dhcp_enabled: true
          pihole_sync_source: true

        shack-dns-p002:
          ansible_host: 10.0.0.7
          dns_keepalived_priority: 100
          pihole_dhcp_enabled: false
          pihole_sync_source: false
