---
keepalived_vip: "{{ dns_virtual_ip }}"

keepalived_interface: "{{ dns_interface }}"

keepalived_router_id: 51

keepalived_auth_type: "PASS"
keepalived_auth_pass: "dnscluster"

keepalived_check_script: "/usr/local/bin/check-pihole.sh"
