---
pihole_sync_source: false

pihole_sync_user: "shackadmin"
pihole_sync_destination_user: "shackadmin"

pihole_sync_ssh_directory: "/home/shackadmin/.ssh"
pihole_sync_ssh_private_key: "{{ pihole_sync_ssh_directory }}/pihole_gravity_sync"
pihole_sync_ssh_public_key: "{{ pihole_sync_ssh_private_key }}.pub"

pihole_sync_destination_host: "shack-dns-p002"

pihole_sync_database: "/etc/pihole/gravity.db"
