---
- name: Get SSH user
  ansible.builtin.command: whoami
  register: ssh_user
  changed_when: false
  become: false

- name: Get effective user
  ansible.builtin.command: whoami
  register: effective_user
  changed_when: false

- name: Show user information
  ansible.builtin.debug:
    msg:
      - "SSH user: {{ ssh_user.stdout }}"
      - "Effective user: {{ effective_user.stdout }}"

# - name: Update apt cache
#   ansible.builtin.apt:
#     update_cache: true
#     cache_valid_time: 3600

# - name: Install base packages
#   ansible.builtin.apt:
#     name: "{{ dns_base_packages }}"
#     state: present

# - name: Set timezone
#   community.general.timezone:
#     name: Europe/Brussels

# - name: Ensure hostname is configured
#   ansible.builtin.hostname:
#     name: "{{ inventory_hostname }}"

# - name: Ensure hostname is present in /etc/hosts
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     regexp: "^127\\.0\\.1\\.1\\s+"
#     line: "127.0.1.1 {{ inventory_hostname }}"
#     create: true
#     mode: "0644"
