---
- name: Check effective user
  ansible.builtin.command: id
  register: dns_effective_user
  changed_when: false

- name: Show effective user
  ansible.builtin.debug:
    var: dns_effective_user.stdout

- name: Test privilege escalation
  ansible.builtin.command: whoami
  become: true
  register: become_test
  changed_when: false

- name: Show privilege escalation result
  ansible.builtin.debug:
    var: become_test.stdout

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

# - name: Install base packages
#   ansible.builtin.apt:
#     name: "{{ dns_base_packages }}"
#     state: present

# - name: Set timezone
#   community.general.timezone:
#     name: Europe/Brussels

# - name: Ensure hostname is configured
#   ansible.builtin.hostname:
#     name: "{{ inventory_hostname }}"

# - name: Ensure hostname is present in /etc/hosts
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     regexp: "^127\\.0\\.1\\.1\\s+"
#     line: "127.0.1.1 {{ inventory_hostname }}"
#     create: true
#     mode: "0644"
