---
pihole_install_url: "https://install.pi-hole.net"

pihole_config_dir: "/etc/pihole"
pihole_config_file: "{{ pihole_config_dir }}/pihole.toml"

pihole_user: "pihole"
pihole_group: "pihole"

pihole_interface: "{{ dns_interface }}"

pihole_web_port: 80

pihole_upstream_dns:
  - "127.0.0.1#{{ unbound_port }}"

pihole_domain: "{{ dns_domain }}"

pihole_query_logging: true

pihole_privacy_level: 0
