---
# DNS cluster
dns_virtual_ip: 10.0.0.5
dns_primary_ip: 10.0.0.6
dns_secondary_ip: 10.0.0.7
dns_interface: eth0

# Host network configuration
dns_netmask: 255.255.255.0
dns_gateway: 10.0.0.1

# DNS
dns_domain: home.arpa
dns_listen_port: 53

# Unbound
unbound_port: 5335

# Pi-hole
pihole_web_port: 80

pihole_dhcp_start: "10.0.0.100"
pihole_dhcp_end: "10.0.0.250"
pihole_dhcp_router: "10.0.0.1"
pihole_dhcp_netmask: "255.255.255.0"
pihole_dhcp_lease_time: "24h"
pihole_dhcp_dns: "10.0.0.5"

pihole_sync_enabled: true
pihole_sync_source: "10.0.0.6"
pihole_sync_destination: "10.0.0.7"
pihole_sync_user: "pihole"
pihole_sync_ssh_key: "/var/lib/pihole/.ssh/gravity_sync"
pihole_sync_destination_host: "shack-dns-p002"

# Keepalived
keepalived_vip: "{{ dns_virtual_ip }}"
keepalived_interface: "{{ dns_interface }}"
keepalived_router_id: 51

keepalived_auth_type: "PASS"
keepalived_auth_pass: "dnscluster"
keepalived_check_script: "/usr/local/bin/check-pihole.sh"
